### PR TITLE
Update to web3==5.28.

### LINKED ISSUE #2770: Bug report: Dependecies conflict using aea-ledger-ethereum
### Prerequisites

- [X] I am running the [latest version of the AEA Framework](https://docs.fetch.ai/aea/version/).
- [X] I checked the [documentation](https://docs.fetch.ai/aea/) and found no answer to my problem.
- [X] I checked the [existing issues](https://github.com/fetchai/agents-aea/issues) to make sure my problem has not already been reported.
- [X] I have read the [code of conduct](https://github.com/fetchai/agents-aea/blob/main/CODE_OF_CONDUCT.md) before creating this issue.

### Expected Behavior

To work well when installing ocean-lib==1.2.0 and aea-ledger-ethereum==1.10

### Current Behavior

`ocean-lib` does not use a lower version than 5.20 for web3 and `aea-ledger-ethereum` requires web3==5.12 and that generates dependency conflict.

### To Reproduce

Try installing in a python environment the following dependencies:
```console
pipenv --python 3.8
pipenv shell
pipenv install --skip-lock ocean-lib==1.2.0
pipenv install --skip-lock aea-ledger-ethereum ==1.1.0
```

### Context

Operating system: Ubuntu 20.04, Python 3.8

### Failure Logs

```
[pipenv.exceptions.InstallError]: The conflict is caused by:
[pipenv.exceptions.InstallError]:     aea-ledger-ethereum 1.1.0 depends on web3==5.12.0
[pipenv.exceptions.InstallError]:     ocean-lib 1.2.0 depends on web3==5.28.0
[pipenv.exceptions.InstallError]: ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

### PR DESCRIPTION
**Pull request by mariacarmina**
## Proposed changes
Updated web3 version to 5.28 in Pipfile, setup.py from aea-ledger-ethereum & tox.ini.

## Fixes

Fixes #2770

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](https://github.com/fetchai/agents-aea/blob/main/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [ ] Lint and unit tests pass locally with my changes and CI passes too
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by AnaLoznianu** [comment]
This is a highly needed update! Thanks for opening this PR 👍

**Comment by AnaLoznianu** [comment]
@fetchTeam can you please review it?

**Comment by mariacarmina** [comment]
Can someone from approve the running workflows, please? Some other dependency conflicts occurred when trying to update to web3==5.28.0 and I have fixed them locally.

**Comment by mariacarmina** [comment]
@solarw this is the PR that includes some of the modifications that you proposed as well on #2774. I had some issues with the doc links check.

Can someone approve the workflows again, please?

**Comment by 5A11** [comment]
@mariacarmina @AnaLoznianu We have created another PR, subsuming what's in this PR, which is now merged (https://github.com/fetchai/agents-aea/pull/2774). This is because we are in the process of upgrading the whole dependency management system in AEAs into Poetry. Those changes are now in the `feature/poetry-mypy-fixes` branch along with the rest of the deps management rework. You can use it or wait until it gets into the next release. 

Closing this PR now.

**Comment by AnaLoznianu** [comment]
@5A11 Thanks for the update :)
When are you planning to do the next release? I'm asking to know how we should proceed

**Pull request closed without merging**
