### PR TITLE
AEA-1573 Improve unhelpful error messages (#2482)

### LINKED ISSUE #2482: Examples of unhelpful error messages
**Is your feature request related to a problem? Please describe.**
This issue lists unhelpful error messages so they can be made more informative.

**Describe the solution you'd like**
Make them informative and actionable

Screenshot 2021-04-29 at 14 15 51

### PR DESCRIPTION
**Pull request by marcofavorito**
## Proposed changes

Improve some unhelpful error messages listed in #2482

## Fixes

Fix #2482

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [ ] Lint and unit tests pass locally with my changes and CI passes too
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

n/a

### CODE REVIEW

**Review by DavidMinarsch — APPROVED** [review]
LGTM

**Review by DavidMinarsch — CHANGES_REQUESTED** [review]
Tests don't pass on Windows.

**Review by DavidMinarsch — APPROVED** [review]
LGTM

**Review by solarw — APPROVED** [review]
LGTM

**Pull request merged**
