### PR TITLE
Add option to return AEA logs in missing string check (AEA-1636)

### PR DESCRIPTION
**Pull request by jrriehl**
## Proposed changes

Currently it's hard to debug tests that fail only in CI because the AEA logs are not visible. This PR adds an option to return the AEA logs so they can be reported on test failures.

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [x] Lint and unit tests pass locally with my changes and CI passes too
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by DavidMinarsch — CHANGES_REQUESTED** [review]
@jrriehl this PR is backwards-incompatible as it changes the API of the test case. I suggest either logging the stdout directly or just making it accessible via a property (i.e. adding to rather than changing the API).

**Comment by jrriehl** [comment]
> @jrriehl this PR is backwards-incompatible as it changes the API of the test case. I suggest either logging the stdout directly or just making it accessible via a property (i.e. adding to rather than changing the API).

@DavidMinarsch I added an optional argument `return_logs` that defaults to `False` in which case the function performs exactly as before. Only when set to `True`, the function returns a different type, so I think this is backwards compatible. Or am I missing something?

**Comment by jrriehl** [comment]
Okay, I see now that `stdout` is already accessible via a property, which is indeed a simpler solution. I will using this approach.

**Review by DavidMinarsch — APPROVED** [review]
LGTM

**Pull request merged**
