### PR TITLE
Fixed web3 dependency for aea-ledger-ethereum.

### PR DESCRIPTION
**Pull request by mariacarmina**
## Proposed changes
Updated version range for web3 in `aea-ledger-ethereum` plugin.

## Issues

Links to any issues resolved.

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to stop working as expected)
- [x] Something else (e.g. test, package, script, example, deployment, infrastructure, ...)

## Checklist

_Put an `x` in the boxes that apply._

- [X] I have read the [CONTRIBUTING](https://github.com/fetchai/agents-aea/blob/main/CONTRIBUTING.md) document.
- [X] I have based my branch, and I am making a pull request against, the `develop` branch.
- [X] Lint and unit tests pass locally with my changes.

### If applicable

- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have checked that code coverage does not decrease.
- [ ] I have added/updated the documentations.
- [ ] Dependent changes have been merged and published in downstream modules.

## Further comments
Output of dependency conflict:
```
[pipenv.exceptions.InstallError]: The conflict is caused by:
[pipenv.exceptions.InstallError]:     aea-ledger-ethereum 1.1.1 depends on web3<6.0.0 and >=5.31.0
[pipenv.exceptions.InstallError]:     eth-brownie 1.19.1 depends on web3==5.30.0
```

### CODE REVIEW

**Comment by mariacarmina** [comment]
I think this fix should be included in `pyproject.toml` as well https://github.com/fetchai/agents-aea/blob/main/pyproject.toml#L101. What do you think @5A11?

**Comment by 5A11** [comment]
@mariacarmina The new deps range fails on tests and is not backwards compatible. Need to either fix the tests (`test_session_cache()`) in the PR (add backwards compatibility to the `aea-ledger-ethereum` plugin for web3 `5.30.0`) or maybe look into upgrading what you are using that needs this older version of `web3py`.

**Comment by mariacarmina** [comment]
> @mariacarmina The new deps range fails on tests and is not backwards compatible. Need to either fix the tests (`test_session_cache()`) in the PR (add backwards compatibility to the `aea-ledger-ethereum` plugin for web3 `5.30.0`) or maybe look into upgrading what you are using that needs this older version of `web3py`.

I think I needed to update the web3 only the setup.py from `aea-ledger-ethereum`

**Comment by mariacarmina** [comment]
Resolved the dependency issue updating ocean-lib. Thanks, will close this.

**Pull request closed without merging**
