### PR TITLE
protocol generator: type hint for dialogue valid replies

### PR DESCRIPTION
**Pull request by solarw**
## Proposed changes

protocol generator: type hint for dialogue valid replies

## Fixes

https://github.com/fetchai/agents-aea/issues/2448

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [x] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [x] Lint and unit tests pass locally with my changes and CI passes too
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that code coverage does not decrease.
- [x] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by DavidMinarsch — APPROVED** [review]
LGTM

**Review by DavidMinarsch — DISMISSED** [review]
Hashes don't pass in CI

**Comment by 5A11** [comment]
This LGTM. but how come we don't need the same for other variables, e.g. `INITIAL_PERFORMATIVES`, `TERMINAL_PERFORMATIVES`, etc.

**Comment by DavidMinarsch** [comment]
> This LGTM, but how come we don't need the same for other variables, e.g. `INITIAL_PERFORMATIVES`, `TERMINAL_PERFORMATIVES`, etc.

Good point! @solarw I suggest adding type hints for these too!

**Comment by solarw** [comment]
> > This LGTM, but how come we don't need the same for other variables, e.g. `INITIAL_PERFORMATIVES`, `TERMINAL_PERFORMATIVES`, etc.
> 
> Good point! @solarw I suggest adding type hints for these too!

updated.

for some reason those properties were ok for mypy

**Review by 5A11 — APPROVED** [review]
lgtm

**Comment by solarw** [comment]
> Hashes don't pass in CI

updated

**Review by 5A11 — APPROVED** [review]

**Review by jrriehl — APPROVED** [review]

**Pull request merged**
