### PR TITLE
benchmarks: agents contruction, decision maker

### PR DESCRIPTION
**Pull request by solarw**
## Proposed changes

benchmarks: agents contruction, decision maker

## Fixes

https://github.com/fetchai/agents-aea/issues/2433

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [ ] Lint and unit tests pass locally with my changes and CI passes too
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by DavidMinarsch — APPROVED** [review]
Looks great! Can you show some of the results from your machine here in comments?

**Comment by solarw** [comment]
$ ./check_decision_maker.py --ledger_id fetchai --amount_of_tx 100 --number_of_runs 10
Start test with options:
* Ledger id: fetchai
* Amount of txs: 100
* Number of runs: 10

Results:
 * run_time (seconds): mean: 0.268922 stdev: 0.007766 variance: 6e-05 
 * rate (envelopes/second): mean: 0.002689 stdev: 7.8e-05 variance: 0.0 
 * mem usage (Mb): mean: 0.292187 stdev: 0.091086 variance: 0.008297 
Test finished.

**Comment by solarw** [comment]
Start test with options:
* Agents: 100
* Number of runs: 3

Results:
 * avg config load time: mean: 0.116683 stdev: 0.000821 variance: 1e-06 
 * avg full construction: mean: 0.141233 stdev: 0.001368 variance: 2e-06 
 * avg build time: mean: 0.02455 stdev: 0.000547 variance: 0.0 
 * agent mem usage (Mb): mean: 17.315104 stdev: 0.029578 variance: 0.000875 
Test finished.

**Review by 5A11 — APPROVED** [review]
lgtm

**Pull request merged**
