### PR TITLE
chore: web3 and ipfsclient dependencies updated

### PR DESCRIPTION
**Pull request by solarw**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request.

## Fixes

If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to agents-aea?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](https://github.com/fetchai/agents-aea/blob/main/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [ ] Lint and unit tests pass locally with my changes and CI passes too
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

DELETE INCLUSIVE THIS AND BELOW FOR STANDARD PR
------

## Release summary

Version number: [e.g. 1.0.1]

## Release details

Describe in short the main changes with the new release.

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](https://github.com/fetchai/agents-aea/blob/master/CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side), from `develop`
- [ ] Lint and unit tests pass locally and in CI
- [ ] I have checked the fingerprint hashes are correct by running (`scripts/generate_ipfs_hashes.py`)
- [ ] I have regenerated the latest API docs
- [ ] I built the documentation and updated it with the latest changes
- [ ] I have added an item in `HISTORY.md` for this release
- [ ] I bumped the version number in the `aea/__version__.py` file.
- [ ] I bumped the version number in every Docker image of the repo and published it. Also, I built and published them with tag `latest`  
      (check the READMEs of [`aea-develop`](https://github.com/fetchai/agents-aea/blob/master/develop-image/README.md#publish) 
      and [`aea-user`](https://github.com/fetchai/agents-aea/blob/master/develop-image/user-image/README.md#publish))
- [ ] I have pushed the latest packages to the registry.
- [ ] I have uploaded the latest `aea` to PyPI.
- [ ] I have uploaded the latest plugins to PyPI.

## Further comments

Write here any other comment about the release, if any.

### CODE REVIEW

**Comment by mariacarmina** [comment]
It is duplicate of #2769. I have updated ipfshttpclient and also eth-account. Should we close one of them?

**Comment by solarw** [comment]
> It is duplicate of #2769. I have updated ipfshttpclient and also eth-account, because I have opened it earlier. I saw that this PR includes other modifications regarding `poetry.lock` file as well. How should we proceed in this situation?



> It is duplicate of #2769. I have updated ipfshttpclient and also eth-account, because I have opened it earlier. I saw that this PR includes other modifications regarding `poetry.lock` file as well. How should we proceed in this situation?

@mariacarmina Appreciate your work, the problem that we have a great rework for dependencies management and updates.
so opened a dedicated PR that fits poetry deps management.

Sure, we can merge your PR, but anyway will replace it with poetry based one.

Thanks a lot for contribution and sorry for some updates not compatible with your branch.

**Comment by AnaLoznianu** [comment]
@solarw Thanks for the updates, I appreciate you taking this over.
Do you have a timeline in mind? when can we expect to have this integrated into the main branch? 

I am asking because we worked for a few months on integrating with the fetch.ai ecosystem and having our agents run, and the last blocker we have is this web3 update. Would really love to be able to release to production soon.

Thank you very much!

**Comment by solarw** [comment]
> @solarw Thanks for the updates, I appreciate you taking this over. Do you have a timeline in mind? when can we expect to have this integrated into the main branch?
> 
> I am asking because we worked for a few months on integrating with the fetch.ai ecosystem and having our agents run, and the last blocker we have is this web3 update. Would really love to be able to release to production soon.
> 
> Thank you very much!

planned to merged it in this week.

**Comment by AnaLoznianu** [comment]
> planned to merged it in this week.
Great to hear, thank you very much! 🙏

**Pull request merged**
