### PR TITLE
aea cli autocompletition support

### PR DESCRIPTION
**Pull request by solarw**
## Proposed changes

aea cli autocompletition support

## Fixes

https://github.com/fetchai/agents-aea/issues/1640

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `develop` branch (left side). Also you should start your branch off our `develop`.
- [ ] Lint and unit tests pass locally with my changes and CI passes too
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that code coverage does not decrease.
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

DELETE INCLUSIVE THIS AND BELOW FOR STANDARD PR
------

## Release summary

Version number: [e.g. 1.0.1]

## Release details

Describe in short the main changes with the new release.

## Checklist

_Put an `x` in the boxes that apply._

- [ ] I have read the [CONTRIBUTING](../CONTRIBUTING.md) doc
- [ ] I am making a pull request against the `main` branch (left side), from `develop`
- [ ] Lint and unit tests pass locally and in CI
- [ ] I have checked the fingerprint hashes are correct by running (`scripts/generate_ipfs_hashes.py`)
- [ ] I have regenerated the latest API docs
- [ ] I built the documentation and updated it with the latest changes
- [ ] I have added an item in `HISTORY.md` for this release
- [ ] I bumped the version number in the `aea/__version__.py` file.
- [ ] I bumped the version number in every Docker image of the repo and published it. Also, I built and published them with tag `latest`  
      (check the READMEs of [`aea-develop`](../develop-image/README.md#publish) 
      and [`aea-user`](../user-image/README.md#publish))
- [ ] I have pushed the latest packages to the registry.
- [ ] I have uploaded the latest `aea` to PyPI.
- [ ] I have uploaded the latest plugins to PyPI.

## Further comments

Write here any other comment about the release, if any.

### CODE REVIEW

**Review by DavidMinarsch — APPROVED** [review]
LGTM

**Comment by 5A11** [comment]
I think having to use a cli command to enable autocomplete is a bit clunky. Would be more natural if it is on by default. 

@solarw mentioned it is not possible to run the script automatically when installing aea from PyPI to have it on by default. Is there maybe another way? e.g. enabling it on the `aea init` which users have to run first on installing the framework.

**Comment by DavidMinarsch** [comment]
> I think having to use a cli command to enable autocomplete is a bit clunky. Would be more natural if it is on by default and a user can decide to use/not use it.
> 
> @solarw mentioned it is not possible to run the script automatically when installing aea from PyPI to have it on by default. Is there maybe another way? e.g. enabling it on the `aea init` which every user runs once after installing the framework?

Yes we could make it run on `aea init`. If we do that, then we should add a flag in aea init to disable it running. By default it will run.

**Comment by 5A11** [comment]
I tried the current implementation of the autocomplete and it is very slow. Autocomplete is supposed to be there to save time for the user writing a complete command by pressing tab. In the current implementation, it is actually faster to write whole commands than wait for autocomplete to complete them. For this reason, I don't think we should merge this PR.

We should come up with a solution that is a) on by default (doesn't need to be manually turned on) and b) is fast (similar speeds to the autocompletion of file names on unit systems). @solarw suggests it may be possible to achieve this using the current click approach which he'll explore, otherwise he can explore other approaches.

**Comment by DavidMinarsch** [comment]
Ok makes sense - let's close this then!

**Pull request closed without merging**
